/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package geoCaching;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shimal
 */
public class FindGeocache extends javax.swing.JFrame {
    
    // Get the size of the screen
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form FindGeocache
     */
    public FindGeocache() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCountry = new javax.swing.JButton();
        btnCountry.setOpaque(false);
        btnCountry.setContentAreaFilled(false);
        btnCountry.setBorderPainted(false);
        btnCity = new javax.swing.JButton();
        btnCity.setOpaque(false);
        btnCity.setContentAreaFilled(false);
        btnCity.setBorderPainted(false);
        btnArea = new javax.swing.JButton();
        btnArea.setOpaque(false);
        btnArea.setContentAreaFilled(false);
        btnArea.setBorderPainted(false);
        btnBack = new javax.swing.JButton();
        btnBack.setOpaque(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 605, 748));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 605, 748));
        setMaximumSize(new java.awt.Dimension(605, 748));
        setMinimumSize(new java.awt.Dimension(605, 748));
        getContentPane().setLayout(null);

        btnCountry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/btn_country.png"))); // NOI18N
        btnCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountryActionPerformed(evt);
            }
        });
        getContentPane().add(btnCountry);
        btnCountry.setBounds(130, 120, 320, 160);

        btnCity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/btn_city.png"))); // NOI18N
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityActionPerformed(evt);
            }
        });
        getContentPane().add(btnCity);
        btnCity.setBounds(140, 310, 310, 180);

        btnArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/btn_area.png"))); // NOI18N
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });
        getContentPane().add(btnArea);
        btnArea.setBounds(150, 510, 300, 150);

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/btn_back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 30, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find_background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 710);
        this.setLocation((dim.width-this.getSize().width)/2, (dim.height-this.getSize().height)/2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityActionPerformed
        Queries query = new Queries();
        query.findGeocachers(query.getCity(), query.findUserLocation(Login.username, query.getCacherCity()));
    }//GEN-LAST:event_btnCityActionPerformed

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed
        Queries query = new Queries();
        query.findGeocachers(query.getArea(), query.findUserLocation(Login.username, query.getCacherArea()));
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountryActionPerformed
        Queries query = new Queries();
        query.findGeocachers(query.getCountry(), query.findUserLocation(Login.username, query.getCacherCountry()));
    }//GEN-LAST:event_btnCountryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindGeocache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindGeocache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindGeocache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindGeocache.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindGeocache().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCity;
    private javax.swing.JButton btnCountry;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
