/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package geoCaching;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Shimal
 */
public class Registration extends javax.swing.JFrame {
    
    // Get the size of the screen
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();    

    
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeoCachingPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("GeoCachingPU").createEntityManager();
        geocacherstblQuery = java.beans.Beans.isDesignTime() ? null : GeoCachingPUEntityManager.createQuery("SELECT g FROM Geocacherstbl g");
        geocacherstblList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : geocacherstblQuery.getResultList();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        btnAddNewUser = new javax.swing.JButton();
        btnAddNewUser.setOpaque(false);
        btnAddNewUser.setContentAreaFilled(false);
        btnAddNewUser.setBorderPainted(false);
        btnDate = new com.toedter.calendar.JDateChooser();
        btnBack = new javax.swing.JButton();
        btnBack.setOpaque(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setBorderPainted(false);
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        dropdownGender = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setBounds(new java.awt.Rectangle(0, 0, 776, 860));
        setMaximumSize(new java.awt.Dimension(776, 860));
        setMinimumSize(new java.awt.Dimension(776, 860));
        setPreferredSize(new java.awt.Dimension(776, 860));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 190, 110, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 300, 60, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Country");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 360, 60, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("D.O.B");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 550, 50, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 240, 70, 15);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(330, 180, 206, 33);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(330, 240, 206, 33);
        getContentPane().add(txtCountry);
        txtCountry.setBounds(330, 360, 206, 33);

        btnAddNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/btn_register.png"))); // NOI18N
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddNewUser);
        btnAddNewUser.setBounds(310, 680, 123, 44);
        getContentPane().add(btnDate);
        btnDate.setBounds(330, 560, 206, 30);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buttons/btn_back.png"))); // NOI18N
        btnBack.setToolTipText("");
        btnBack.setDoubleBuffered(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(20, 50, 130, 41);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Area");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 470, 40, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("City");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(220, 420, 30, 15);
        getContentPane().add(txtCity);
        txtCity.setBounds(330, 430, 206, 33);
        getContentPane().add(txtArea);
        txtArea.setBounds(330, 490, 206, 33);

        dropdownGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Other" }));
        dropdownGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownGenderActionPerformed(evt);
            }
        });
        getContentPane().add(dropdownGender);
        dropdownGender.setBounds(330, 300, 206, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/register_background.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -90, 760, 1000);
        this.setLocation((dim.width-this.getSize().width)/2, (dim.height-this.getSize().height)/2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed
        register(btnDate.getDate(), txtUsername.getText(), txtPassword.getText(), txtCountry.getText(), txtCity.getText(), txtArea.getText(), getGender(dropdownGender));            
        Login.setUsername(txtUsername.getText()); // Logging user in
        new Home().setVisible(true); 
        this.setVisible(false);
        
    }//GEN-LAST:event_btnAddNewUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Login().setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void dropdownGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownGenderActionPerformed
        
    }//GEN-LAST:event_dropdownGenderActionPerformed

    /**
     * @param args the command line arguments
     */
    
 
    
    public static void main(String args[]) {
       
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
                
                
            }
        });
    }
    
    public String getGender(JComboBox dropdown) {
        String gender = "2";
        int id = dropdown.getSelectedIndex();
        
        switch (id) {
            case 0:
                gender = "M"; 
                break;
            case 1 :
                gender = "F"; 
                break;
            case 2 :
                gender = "O"; 
                break;
               
        }
        
        return gender;
    }
    
    public String IDgenerator(String username, Date date, String gender) { // Algorithm to generate cacherID  

        String firstLetter = String.valueOf(username.charAt(0)); // Getting first letter of cacherID from username        
        Calendar cal = Calendar.getInstance(); // Getting next 4 numbers of cacherID from D.O.B
        cal.setTime(date); // Setting calendar to "date"
        int Year = cal.get(Calendar.YEAR); // Getting Year        
        String tempInt = Integer.toString(Year); // Converting int "Year" to String to dlete first to digits
        int next2Digits = Integer.parseInt(Integer.toString(Year).substring(0, 2)); // Deleting first 2 digits from int "Year"        
        Random num = new Random(); // Genearting random digit number
        int last3Digits = num.nextInt((999 - 0) + 1) + 0;
        String ID = firstLetter + next2Digits + last3Digits + "";
        return ID;

    }
    
    public void register(Date date, String username, String password, String country, String city, String area, String gender) {
        
        Geocacherstbl newUser = new Geocacherstbl(IDgenerator(username, date, gender), date, username, password, country, city, area, gender);
        GeoCachingPUEntityManager.getTransaction().begin(); // Using persistance unit to begin transaction
        GeoCachingPUEntityManager.persist(newUser); // Updating database with new user
        GeoCachingPUEntityManager.getTransaction().commit(); // Commiting the changes to the database     
               
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager GeoCachingPUEntityManager;
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnBack;
    private com.toedter.calendar.JDateChooser btnDate;
    private javax.swing.JComboBox dropdownGender;
    private java.util.List<geoCaching.Geocacherstbl> geocacherstblList;
    private javax.persistence.Query geocacherstblQuery;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
